# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'E-Learning' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for E-Learning
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'SideMenu'
  pod 'Toast-Swift', '~> 2.0.0'
  pod 'IQKeyboardManagerSwift'
  pod 'Material', '~> 2.0'
  pod 'MMPlayerView', '~> 2.1.8'
  pod 'DateTimePicker’, '~> 1.1.4'

  target 'E-LearningTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'E-LearningUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
